[general]
email = rahul.kumeriya@outlook.com

[server]
headless = true
enableCORS=false
port = $PORT


[theme]
primaryColor=#2214c7
backgroundColor=#ffffff
secondaryBackgroundColor=#e8eef9
textColor=#000000
font=sans serif